package common

import (
	"bufio"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"

	"github.com/anacrolix/dht/v2/krpc"
	log "github.com/sirupsen/logrus"
)

// MonitorReportToFile writes the report to the file in path.
// report is a pointer to an output data structure, currently only generated by the monitor.
func MonitorReportToFile(report *Output, path string) {
	var nodes []*MonitoredNodeJSON
	for _, node := range report.Nodes {
		jsonFormatted := MonitoredNodeJSON{UDPAddrs: node.UDPAddr, Reachable: node.Reachable, IPVersion: node.IPVersion.String()}
		nodes = append(nodes, &jsonFormatted)
	}

	MonitorOutput := MonitorOutputJSON{StartDate: report.StartDate, EndDate: report.EndDate, Nodes: nodes}

	vf, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0666)
	if os.IsNotExist(err) {
		if err := os.MkdirAll(filepath.Dir(path), 0777); err != nil {
			log.Errorf("Error creating file %s\n", err)
			os.Exit(1)
		}
		vf, err = os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0666)
		if err != nil {
			log.Errorf("Error opening file %s\n", err)
			os.Exit(1)
		}
	} else if err != nil {
		panic(err)
	}
	defer vf.Close()

	err = json.NewEncoder(vf).Encode(MonitorOutput)
	if err != nil {
		log.WithField("err", err).Error("Could not encode JSON and/or write to output file.")
	}
}

func CrawlReportToFile(report *CrawlOutput, onlineOnly bool, path string) {
	var nodes []*CrawledNodeJSON
	for _, node := range report.Nodes {
		if onlineOnly {
			if node.Reachable {
				jsonFormatted := CrawledNodeJSON{NID: node.NID, UDPAddrs: node.UDPAddrs, Reachable: node.Reachable, IPVersion: node.IPVersion.String()}
				nodes = append(nodes, &jsonFormatted)
			}
		} else {
			jsonFormatted := CrawledNodeJSON{NID: node.NID, UDPAddrs: node.UDPAddrs, Reachable: node.Reachable, IPVersion: node.IPVersion.String()}
			nodes = append(nodes, &jsonFormatted)
		}
	}

	crawlOutput := CrawlOutputJSON{StartDate: report.StartDate, EndDate: report.EndDate, Nodes: nodes}

	vf, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0666)
	if os.IsNotExist(err) {
		if err := os.MkdirAll(path, 0777); err != nil {
			panic(err)
		}
		vf, err = os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0666)
		if err != nil {
			panic(err)
		}
	} else if err != nil {
		panic(err)
	}
	defer vf.Close()

	err = json.NewEncoder(vf).Encode(crawlOutput)
	if err != nil {
		log.WithField("err", err).Error("Could not encode JSON and/or write to output file.")
	}
}

// CreateDirIfNotExists creates the directory described in path if it does not exist yet.
func CreateDirIfNotExists(path string) error {
	_, err := os.Stat(path)
	if os.IsNotExist(err) {
		os.MkdirAll(path, 0777)
		return nil
	}
	return err
}

// ReadBootstrapListFromFile parses a file containing bootstrap peers. It assumes a text file with an IP:Port address on each line.
// It will ignore lines starting with a comment "//"
func ReadBootstrapListFromFile(path string) ([]*krpc.NodeInfo, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	// Read the file line by line and parse the multiaddress string
	var bootstrapNI []*krpc.NodeInfo
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		// Ignore lines that are commented out
		if strings.HasPrefix(line, "//") {
			continue
		}
		// Remove any whitespaces (esp necessary with badly formatted IPv6 addrs)
		addr := strings.Join(strings.Fields(line), "")
		ainfo, err := ParseAddrString(addr)
		if err != nil {
			log.WithField("err", err).Error("Error parsing bootstrap peers.")
			return nil, err
		}
		bootstrapNI = append(bootstrapNI, ainfo)
	}

	return bootstrapNI, nil
}
